import React, {useEffect, useRef, useState} from 'react';
import {Menu, MapPin, Search, Heart, Bell, MessageCircle, UserRound, ChevronDown, Info, List, X, Check, ImagePlus, Sparkles, ArrowLeft, Download, GripVertical} from 'lucide-react';
import '@fontsource/noto-sans-kr/korean-400.css';
import '@fontsource/noto-sans-kr/korean-600.css';
import '@fontsource/noto-sans-kr/latin-400.css';
import '@fontsource/noto-sans-kr/latin-600.css';
const asset = name => `${import.meta.env.BASE_URL}assets/${name}`;
const initial={description:'',title:'',price:'',address:'',seller:'개인',condition:'중고',brand:'',model:'',year:'',type:'',km:'',capacity:'',origin:'',warranty:'',showDocument:false};
const years=[...Array.from({length:46},(_,i)=>String(2026-i)),'1980년 이전'];
function dbAction(mode,value){return new Promise((resolve,reject)=>{const req=indexedDB.open('chotot-korean-form',1); req.onupgradeneeded=()=>req.result.createObjectStore('drafts'); req.onerror=()=>reject(req.error); req.onsuccess=()=>{const db=req.result;const tx=db.transaction('drafts',mode);const q=value===undefined?tx.objectStore('drafts').get('current'):tx.objectStore('drafts').put(value,'current');let result;q.onsuccess=()=>result=q.result;tx.oncomplete=()=>{db.close();resolve(result)};tx.onerror=()=>{db.close();reject(tx.error)}}})}
function Modal({title,onClose,children}){const ref=useRef();useEffect(()=>{const old=document.activeElement;ref.current.showModal();return()=>old?.focus()},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===ref.current)onClose()}}><div className="modal-head"><h2>{title}</h2><button className="icon-button" aria-label="닫기" onClick={onClose}><X/></button></div>{children}</dialog>}
function Media({item}){const [url,setUrl]=useState('');useEffect(()=>{const u=URL.createObjectURL(item);setUrl(u);return()=>URL.revokeObjectURL(u)},[item]);return item.type.startsWith('video/')?<video src={url || undefined} controls/>:<img src={url || undefined} alt={item.name}/>}
export function App(){
 const [form,setForm]=useState(initial),[files,setFiles]=useState([]),[documentFile,setDocumentFile]=useState(null),[details,setDetails]=useState(false),[errors,setErrors]=useState({}),[modal,setModal]=useState(''),[notice,setNotice]=useState(''),[draft,setDraft]=useState(null),[dragged,setDragged]=useState(null),[previewIndex,setPreviewIndex]=useState(0),[address,setAddress]=useState('');
 const input=useRef(),docInput=useRef(),formRef=useRef();
 const update=(name,value)=>{setForm(f=>({...f,[name]:value}));setErrors(e=>({...e,[name]:''}))};
 useEffect(()=>{dbAction('readonly').then(v=>v&&setDraft(v)).catch(()=>{});},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5500);return()=>clearTimeout(t)},[notice]);
 const notify=msg=>setNotice(msg);
 function addFiles(list){const incoming=Array.from(list);const valid=incoming.filter(f=>/^(image|video)\//.test(f.type));if(valid.length!==incoming.length)notify('사진 또는 동영상 파일만 선택해 주세요.');const combined=[...files];for(const f of valid){const kind=f.type.split('/')[0],limit=kind==='image'?20:1;if(combined.filter(v=>v.type.startsWith(kind+'/')).length>=limit){notify('사진은 최대 20장, 동영상은 1개까지 추가할 수 있습니다.');continue;}combined.push(f)}setFiles(combined);setErrors(e=>({...e,media:''}));}
 function validate(full=true){const e={};if(!files.some(f=>f.type.startsWith('image/')))e.media='사진을 1장 이상 추가해 주세요.';if(!form.description.trim())e.description='판매글 설명을 입력해 주세요.';if(full){for(const key of ['title','address','brand','model','year','type'])if(!form[key].trim())e[key]='필수 항목을 입력해 주세요.';if(Number(form.price)<1000000)e.price='1,000,000동 이상 입력해 주세요.';if(form.km===''||!Number.isFinite(Number(form.km))||Number(form.km)<0)e.km='0 이상의 주행거리를 입력해 주세요.';}setErrors(e);if(Object.keys(e).length){notify('표시된 필수 항목을 확인해 주세요.');setTimeout(()=>formRef.current?.querySelector('[aria-invalid="true"]')?.focus(),0);return false}return true}
 function next(){if(validate(false)){setDetails(true);notify('차량의 상세 정보를 입력해 주세요.')}}
 async function save(){try{const saved={form,files,documentFile,details,savedAt:new Date().toISOString()};await dbAction('readwrite',saved);setDraft(saved);notify('사진과 입력 내용을 이 브라우저에 임시 저장했습니다.')}catch{notify('저장 공간이 부족하거나 브라우저에서 저장을 허용하지 않습니다.')}}
 const restore=()=>{setForm({...initial,...draft.form});setFiles(draft.files||[]);setDocumentFile(draft.documentFile||null);setDetails(draft.details||false);setErrors({});setModal('');notify('임시 저장한 내용을 불러왔습니다.')};
 function download(){const payload={...form,category:'차량 / 오토바이',currency:'VND',images:files.map(f=>f.name),document:documentFile?.name||null};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='판매글-한국어.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const openPreview=()=>{setPreviewIndex(0);setModal('preview')};
 function Field({name,label,required=false,type='text',options,suffix,readOnly=false}){return <div className={'field-wrap '+(errors[name]?'has-error':'')}><label className="field"><span>{label}{required&&<b> *</b>}</span>{options?<select value={form[name]} onChange={e=>update(name,e.target.value)} aria-invalid={!!errors[name]}><option value="">선택해 주세요</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select>:<input value={form[name]} readOnly={readOnly} type={type} min={type==='number'?0:undefined} step={type==='number'?1:undefined} onChange={e=>update(name,e.target.value)} aria-invalid={!!errors[name]} placeholder={label+' 입력'} />}{suffix&&<em>{suffix}</em>}</label>{errors[name]&&<small className="error">{errors[name]}</small>}</div>}
 const field=(name,label,required=false,options=null,type='text',suffix=null)=>Field({name,label,required,options,type,suffix});
 return <><header><button className="icon-button" aria-label="메뉴" onClick={()=>setModal('menu')}><Menu size={20}/></button><a href={import.meta.env.BASE_URL} className="logo" aria-label="한국어 등록폼 홈"><img src={asset('logo.png')} alt="Chợ Tốt"/></a><button className="location pill" onClick={()=>{setAddress(form.address);setModal('address')}}><MapPin size={18}/>지역 선택<ChevronDown size={16}/></button><div className="search"><Search size={18}/><input aria-label="상품 검색" placeholder="상품 검색…" onKeyDown={e=>e.key==='Enter'&&notify('이 페이지에서는 오토바이 판매글 등록을 체험할 수 있습니다.')}/><button aria-label="검색" onClick={()=>notify('이 페이지에서는 오토바이 판매글 등록을 체험할 수 있습니다.')}><Search size={17}/></button></div><button className="icon-button desktop" aria-label="관심 목록" onClick={()=>notify('저장된 관심 상품이 없습니다.')}><Heart/></button><button className="icon-button desktop" aria-label="알림" onClick={()=>notify('새로운 알림이 없습니다.')}><Bell/></button><button className="pill desktop" onClick={()=>notify('한국어 체험판에서는 채팅을 제공하지 않습니다.')}><MessageCircle size={18}/>문의</button><button className="pill desktop" onClick={()=>setModal('draft')}>판매글 관리</button><button className="pill yellow desktop" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>판매글 등록</button><button className="icon-button account" aria-label="체험 계정 안내" onClick={()=>setModal('about')}><UserRound/></button></header>
 <main><aside><h2>동영상도 함께 올려 보세요!</h2><p><Check/>판매글 조회수 최대 <strong>2배</strong></p><p><Check/>Chợ Tốt 동영상에 무료 노출</p></aside><form ref={formRef} onSubmit={e=>{e.preventDefault();if(!details)next();else if(validate())setModal('complete')}} noValidate>
 <section className="card"><div className="section-label"><span>사진 / 동영상 {files.length===0&&<span className="muted">(사진 최대 20장, 동영상 1개)</span>}<b> *</b></span><button type="button" className="icon-button small" aria-label="사진 등록 안내" onClick={()=>setModal('media')}><Info size={18}/></button></div>
 <input ref={input} type="file" accept="image/*,video/*" multiple className="hidden-input" onChange={e=>{addFiles(e.target.files);e.target.value=''}}/>
 <div className={'media-area '+(!files.length?'empty':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(e.dataTransfer.files.length)addFiles(e.dataTransfer.files)}}><button type="button" className="upload" aria-label="사진 / 동영상 추가" aria-invalid={!!errors.media} onClick={()=>input.current.click()}><img src={asset('upload-media.png')} alt=""/>{!files.length&&<span>사진 / 동영상 추가</span>}</button>{files.map((f,i)=><div key={i} className="thumbnail" draggable onDragStart={()=>setDragged(i)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();e.stopPropagation();if(dragged!==null){setFiles(old=>{const n=[...old];const [moved]=n.splice(dragged,1);n.splice(i,0,moved);return n});setDragged(null)}}}><Media item={f}/><button type="button" className="remove" aria-label={`${i+1}번째 파일 삭제`} onClick={()=>setFiles(old=>old.filter((_,n)=>n!==i))}><X size={14}/></button>{i===0&&f.type.startsWith('image/')&&<span className="cover">대표 이미지</span>}<button type="button" className="reorder" aria-label={`${i+1}번째 파일을 대표로 설정`} onClick={()=>setFiles(old=>[old[i],...old.filter((_,n)=>n!==i)])}><GripVertical size={12}/></button></div>)}</div>
 {errors.media&&<small className="error">{errors.media}</small>}{files.length>0&&<p className="media-hint">길게 눌러 사진 순서를 바꾸세요 · {files.filter(f=>f.type.startsWith('image/')).length}/20장</p>}
 <div className={'description '+(errors.description?'invalid':'')}><label htmlFor="description">판매글 설명<b> *</b></label><textarea id="description" value={form.description} maxLength={1500} aria-invalid={!!errors.description} onChange={e=>update('description',e.target.value)}/>{!details&&<button type="button" className="assist" onClick={()=>setModal('assist')}><Sparkles size={18}/>설명 작성 도우미</button>}</div><small className={errors.description?'error':'counter'}>{errors.description||`${form.description.length}/1,500자`}</small>
 {!details?<><div className="tips"><strong>이런 내용을 적어 주세요</strong><ul><li>제조사, 모델명, 제조연도</li><li>주행거리, 차량 상태, 판매 가격</li></ul></div>{files.length>0&&form.description.trim()&&<button className="next yellow" type="button" onClick={next}>완료 · 상세 정보 입력</button>}</>:<div className="general-fields">{field('title','판매글 제목',true)}{field('price','판매 가격',true,null,'number','₫')}<div className="field-wrap"><button type="button" className={'field address '+(errors.address?'invalid':'')} aria-invalid={!!errors.address} onClick={()=>{setAddress(form.address);setModal('address')}}><span>거래 주소<b> *</b></span><div>{form.address||'주소 선택'}<ChevronDown size={18}/></div></button>{errors.address&&<small className="error">{errors.address}</small>}</div><div className="choice-line"><span>판매자 유형<b> *</b></span><div className="pills">{['개인','전문 판매자'].map(v=><button type="button" key={v} aria-pressed={form.seller===v} className={form.seller===v?'selected':''} onClick={()=>update('seller',v)}>{v}</button>)}</div></div></div>}
 </section>
 <section className={'card details '+(!details?'locked':'')}>{!details?<><List size={24}/><div><h2>상세 정보</h2><p>사진을 추가하고 설명을 먼저 입력해 주세요.</p></div></>:<><h2>상세 정보</h2><div className="field category"><span>카테고리<b> *</b></span><div>차량 / 오토바이</div></div><div className="document"><div className="section-label"><strong>차량 서류</strong><button type="button" className="icon-button small" aria-label="차량 서류 안내" onClick={()=>setModal('document')}><Info size={18}/></button></div><input ref={docInput} type="file" accept="image/*" className="hidden-input" onChange={e=>{const f=e.target.files[0];if(f?.type.startsWith('image/'))setDocumentFile(f);else if(f)notify('차량 서류는 이미지로 추가해 주세요.');e.target.value=''}}/>{documentFile?<div className="thumbnail"><Media item={documentFile}/><button type="button" className="remove" aria-label="차량 서류 삭제" onClick={()=>setDocumentFile(null)}><X size={14}/></button></div>:<button type="button" className="document-upload" aria-label="차량 서류 사진 추가" onClick={()=>docInput.current.click()}><ImagePlus size={28}/></button>}<label className="document-toggle">판매글에 표시<input type="checkbox" checked={form.showDocument} onChange={e=>update('showDocument',e.target.checked)}/></label></div><div className="detail-grid"><div className="condition"><span>차량 상태<b> *</b></span><div className="pills">{['중고','신차'].map(v=><button key={v} type="button" className={form.condition===v?'selected':''} aria-pressed={form.condition===v} onClick={()=>update('condition',v)}>{v}</button>)}</div></div>{field('brand','제조사',true)}{field('model','모델명',true)}{field('year','제조연도',true,years)}{field('type','차량 종류',true)}{field('km','주행거리',true,null,'number','km')}{field('capacity','배기량',false,['50cc 미만','50~100cc','100~175cc','175cc 초과','잘 모르겠음'])}{field('origin','원산지',false,['베트남','인도','대한민국','태국','일본','중국','미국','독일','대만','기타 국가'])}{field('warranty','보증 기간',false,['1~6개월','7~11개월','1년','2년','3년','3년 초과'])}</div></> }</section>
 <p className="demo-note">한국어 체험판 · 입력한 정보는 Chợ Tốt에 전송되지 않습니다.</p><footer><div>{details&&<><button type="button" onClick={openPreview}>미리보기</button><button type="button" onClick={save}>임시 저장</button></>}<button className="yellow" type="submit">{details?'판매글 등록':'다음'}</button></div></footer></form></main>
 {notice&&<div className="toast" role="status">{notice}</div>}
 {modal&&<Modal title={{preview:'판매글 미리보기',complete:'입력 완료',address:'거래 주소',assist:'설명 작성 도우미',media:'사진 / 동영상 안내',document:'차량 서류 안내',draft:'임시 저장한 판매글',menu:'한국어 등록폼',about:'한국어 체험판'}[modal]} onClose={()=>setModal('')}>
 {modal==='address'&&<div className="modal-body"><p>원본의 베트남 거래 지역과 주소를 한국어 또는 현지어로 입력하세요.</p><label className="modal-label">거래 주소<input autoFocus value={address} onChange={e=>setAddress(e.target.value)} placeholder="예: 호찌민시 1군, 도로명과 건물 번호"/></label><button className="yellow full" disabled={!address.trim()} onClick={()=>{update('address',address.trim());setModal('')}}>주소 적용</button></div>}
 {modal==='assist'&&<div className="modal-body"><p>필수 정보를 빠뜨리지 않도록 아래 양식을 활용해 보세요. 이 체험판은 AI 생성 대신 작성 양식을 제공합니다.</p><div className="help-template">제조사 / 모델명:<br/>제조연도:<br/>주행거리:<br/>차량 상태 및 정비 이력:<br/>판매 가격:<br/>거래 지역:</div><button className="yellow full" onClick={()=>{update('description',(form.description+(form.description?'\n\n':'')+'제조사 / 모델명: \n제조연도: \n주행거리: \n차량 상태 및 정비 이력: \n판매 가격: \n거래 지역: ').slice(0,1500));setModal('')}}>설명에 양식 추가</button></div>}
 {modal==='media'&&<div className="modal-body"><p>사진은 최대 20장, 동영상은 1개까지 추가할 수 있습니다. 차량의 앞·뒤·옆면과 실제 상태가 잘 보이는 사진을 선택하세요.</p><p>사진을 드래그하거나 사진 왼쪽 위 버튼을 눌러 대표 이미지를 바꿀 수 있습니다. 파일은 이 브라우저 안에서만 사용됩니다.</p></div>}
 {modal==='document'&&<div className="modal-body"><p>차량 서류 사진을 추가할 수 있습니다. ‘판매글에 표시’를 선택하면 미리보기에도 함께 표시됩니다.</p></div>}
 {modal==='draft'&&<div className="modal-body">{draft?<><p>{draft.form.title||'제목 없는 판매글'}</p><small>{new Date(draft.savedAt).toLocaleString('ko-KR')} 저장</small><button className="yellow full" onClick={restore}>임시 저장 불러오기</button></>:<p>이 브라우저에 임시 저장한 판매글이 없습니다.</p>}</div>}
 {modal==='complete'&&<div className="modal-body complete"><div className="success-icon"><Check size={32}/></div><h3>판매글 입력을 완료했습니다.</h3><p>체험용 폼으로 실제 판매글은 게시되지 않았습니다. 입력 내용을 파일로 저장할 수 있습니다.</p><button className="yellow full" onClick={download}><Download size={18}/>입력 내용 다운로드</button><button className="full" onClick={openPreview}>미리보기</button></div>}
 {modal==='preview'&&<div className="modal-body preview">{files.length>0?<><div className="preview-media"><Media item={files[Math.min(previewIndex,files.length-1)]}/></div><div className="preview-thumbs">{files.map((f,i)=><button className={i===previewIndex?'active':''} key={i} aria-label={`${i+1}번째 미디어 보기`} onClick={()=>setPreviewIndex(i)}><Media item={f}/></button>)}</div></>:<p>등록된 사진이 없습니다.</p>}<h3>{form.title||'제목을 입력해 주세요'}</h3><strong className="price">{form.price?Number(form.price).toLocaleString('ko-KR')+' ₫':'가격 미입력'}</strong><p className="muted"><MapPin size={15}/>{form.address||'주소 미입력'}</p><dl>{[['차량 상태',form.condition],['제조사 / 모델',`${form.brand} ${form.model}`],['제조연도',form.year],['차량 종류',form.type],['주행거리',form.km!==''?form.km+' km':''],['배기량',form.capacity],['원산지',form.origin],['보증 기간',form.warranty],['판매자',form.seller]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value||'미입력'}</dd></div>)}</dl><h4>판매글 설명</h4><p className="description-text">{form.description||'설명을 입력해 주세요.'}</p>{documentFile&&form.showDocument&&<><h4>차량 서류</h4><div className="preview-media"><Media item={documentFile}/></div></>}<button className="full" onClick={()=>setModal('')}><ArrowLeft size={16}/>계속 수정하기</button></div>}
 {(modal==='about'||modal==='menu')&&<div className="modal-body"><p>Chợ Tốt의 오토바이 등록 화면을 한국어로 재구성한 독립 체험판입니다.</p><p>사진·설명·차량 정보를 입력하고 미리보기와 임시 저장을 이용할 수 있습니다. 가격 단위는 원본과 같은 베트남 동(VND)입니다.</p><button className="yellow full" onClick={()=>{setModal('');window.scrollTo({top:0,behavior:'smooth'})}}>판매글 작성하기</button><button className="full" onClick={()=>setModal('draft')}>임시 저장한 판매글</button></div>}
 </Modal>}
 </>;
}


